# Default values for hello-world-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
registryPullSecrets: quay-registry-secret

backend:
  image:
    repository: quay.io/alfresco/anaxes-hello-world-service
    tag: 0.1-SNAPSHOT
    pullPolicy: Always
    internalPort: 8080
  service:
    name: hello-world-app-backend
    # If running on AWS choose LoadBalancer as service Type
    type: NodePort
    externalPort: 80
  ingress:
    path: /hello-service

