{{ if .Values.dns.create }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.4.5
        args:
        - --source=service
        - --domain-filter={{required "You need to add your dns zone -> dns.domain" .Values.dns.domain}}
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --registry=txt
        - --txt-owner-id={{ .Values.dns.ownerId }}
{{ end }}