apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "hello-world.fullname" . }}-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"  
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ui.ingress.path }}
        backend:
          serviceName: {{ template "hello-world.fullname" . }}-ui
          servicePort: {{ .Values.ui.service.externalPort }}

